cmake_minimum_required(VERSION 3.10)
option(AARCH64 "aarch64" OFF)
option(RISCV64 "riscv64" OFF)
option(LOONGARCH64 "loongarch64" OFF)
option(NIIC "necro" OFF)
option(ENPHT "enpht" OFF)
option(GD32 "gd32" OFF)
option(IPROUTE2 "iproute2" OFF)
if(AARCH64)
    set(march aarch64)
    set(arch a64)
    set(CMAKE_INSTALL_RPATH "$ORIGIN:$ORIGIN/../../third_party/lib_lin_a64")
elseif(RISCV64)
    set(march riscv64)
    set(arch r64)
    set(CMAKE_INSTALL_RPATH "$ORIGIN:$ORIGIN/../../third_party/lib_lin_r64")
elseif(LOONGARCH64)
    set(march loongarch64)
    set(arch l64)
    set(CMAKE_INSTALL_RPATH "$ORIGIN:$ORIGIN/../../third_party/lib_lin_l64")
else(AARCH64)
    set(march x86_64)
    set(arch x64)
    set(CMAKE_INSTALL_RPATH "$ORIGIN:$ORIGIN/../../third_party/lib_lin_x64")
endif(AARCH64)
set(CMAKE_C_COMPILER ${march}-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${march}-linux-gnu-g++)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)
project(driver_test VERSION 4.4.4 LANGUAGES C CXX)
set(CMAKE_INSTALL_PREFIX ..)
configure_file(version.h.in version.h)
if(NIIC)
    add_definitions(-DNIIC)
    set(Necro_DIR ${PROJECT_SOURCE_DIR}/../loong_third_party/necro/lib/cmake/necro)
    find_package(Necro REQUIRED)
    add_library(necro SHARED IMPORTED)
    set_target_properties(necro PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../loong_third_party/necro/ld-linux-aarch64.so.1)
    add_library(necroc SHARED IMPORTED)
    set_target_properties(necroc PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../loong_third_party/necro/libc.so.6)
    add_library(necrocxx SHARED IMPORTED)
    set_target_properties(necrocxx PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../loong_third_party/necro/libstdc++.so.6)
endif(NIIC)
add_library(ncurses SHARED IMPORTED)
set_target_properties(ncurses PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../loong_third_party/ncurses/lib/${march}-linux-gnu/libncurses.so.6)
add_library(tinfo SHARED IMPORTED)
set_target_properties(tinfo PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../loong_third_party/ncurses/lib/${march}-linux-gnu/libtinfo.so.6)
if(ENPHT)
    add_definitions(-DENPHT)
    add_library(hbcanhal_${march} SHARED hobot_can_hal_enpht.c)
elseif(GD32)
    add_definitions(-DGD32)
    add_library(hbcanhal_${march} SHARED hobot_can_hal_gd32.c)
else(ENPHT)
    add_library(hbcanhal_${march} SHARED hobot_can_hal_null.c)
endif(ENPHT)
set_target_properties(hbcanhal_${march} PROPERTIES NO_SONAME ON)
if(ENPHT)
    target_include_directories(hbcanhal_${march} PRIVATE ${PROJECT_SOURCE_DIR}/../loong_third_party/enpht/include)
    target_link_directories(hbcanhal_${march} PRIVATE ${PROJECT_SOURCE_DIR})
    target_link_libraries(hbcanhal_${march} PRIVATE enpht-can)
endif(ENPHT)
if(IPROUTE2)
    add_definitions(-DIPROUTE2)
endif(IPROUTE2)
if(NIIC)
    add_library(loong_driver_sdk_${arch} SHARED common.cpp config_xml.cpp rs232.cpp rs485.cpp canbase.cpp can.cpp canemu.cpp ecat.cxx loong_driver_sdk.cpp)
else(NIIC)
    add_library(loong_driver_sdk_${arch} SHARED common.cpp config_xml.cpp rs232.cpp rs485.cpp canbase.cpp can.cpp canemu.cpp ecat.cpp loong_driver_sdk.cpp)
endif(NIIC)
set_target_properties(loong_driver_sdk_${arch} PROPERTIES NO_SONAME ON)
target_include_directories(loong_driver_sdk_${arch} PRIVATE
    ${PROJECT_BINARY_DIR}
    ${PROJECT_SOURCE_DIR}/../loong_third_party/ethercat-cpp/include
    ${PROJECT_SOURCE_DIR}/../loong_third_party/ethercat/include
    ${PROJECT_SOURCE_DIR}/../loong_third_party/modbus/include
    ${PROJECT_SOURCE_DIR}/../loong_third_party/netlink/include
    ${PROJECT_SOURCE_DIR}/../loong_third_party/tinyxml2/include
)
target_link_directories(loong_driver_sdk_${arch} PRIVATE
    ${PROJECT_SOURCE_DIR}/../loong_third_party/ethercat-cpp/lib
    ${PROJECT_SOURCE_DIR}/../loong_third_party/ethercat/lib
    ${PROJECT_SOURCE_DIR}/../loong_third_party/modbus/lib
    ${PROJECT_SOURCE_DIR}/../loong_third_party/netlink/lib
    ${PROJECT_SOURCE_DIR}/../loong_third_party/tinyxml2/lib
)
if(NIIC)
    target_link_libraries(loong_driver_sdk_${arch} PRIVATE Necro::qiuniu ethercat-cpp modbus_${march} netlink_${march} util_${march} tinyxml2_${march} pthread hbcanhal_${march})
else(NIIC)
    target_link_libraries(loong_driver_sdk_${arch} PRIVATE ethercat_${march} modbus_${march} netlink_${march} util_${march} tinyxml2_${march} pthread hbcanhal_${march})
endif(NIIC)
add_executable(driver_test_${march} driver_test.cpp)
if(LOONGARCH64)
    target_include_directories(driver_test_${march} PRIVATE ${PROJECT_SOURCE_DIR}/../loong_third_party/ncurses/include/loongarch64-linux-gnu)
else(LOONGARCH64)
    target_include_directories(driver_test_${march} PRIVATE ${PROJECT_SOURCE_DIR}/../loong_third_party/ncurses/include)
endif(LOONGARCH64)
if(NIIC)
    target_link_libraries(driver_test_${march} PRIVATE loong_driver_sdk_${arch} ncurses tinfo necro necroc necrocxx)
else(NIIC)
    target_link_libraries(driver_test_${march} PRIVATE loong_driver_sdk_${arch} ncurses tinfo)
endif(NIIC)
install(TARGETS loong_driver_sdk_${arch} hbcanhal_${march} driver_test_${march}
    RUNTIME DESTINATION .
    LIBRARY DESTINATION .
)